<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover"
    />

    <title>Stopwatch</title>

    <!-- PWA Manifest -->
    <link rel="manifest" href="./manifest.json" />

    <!-- iPhone PWA Support -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />
    <link rel="apple-touch-icon" href="./assets/Logo.png" />

    <!-- Expo Web Loader -->
    <script src="https://unpkg.com/expo-router/entry"></script>
  </head>

  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>

    <div id="root"></div>

    <!-- Main bundle generated by Snack export -->
    <script src="./index.js"></script>
  </body>
</html>
